disp('Matlab Memory:');
feature('memstats')

disp(sprintf('Java Memory (MB):\nmax = %5.1f, total = %5.1f, free = %5.1f', ...
    java.lang.Runtime.getRuntime.maxMemory/1e6, ...
java.lang.Runtime.getRuntime.totalMemory/1e6, ...
java.lang.Runtime.getRuntime.freeMemory/1e6));

